version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5555:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=katya
      - POSTGRES_PASSWORD=katya9090
